### ISSUE TITLE
Bug: Management endpoints require Content-Type header even if no request body needed

### ISSUE THREAD

**Issue by nagyesta** [nagyesta/lowkey-vault#1040]
#### Describe the bug

All your endpoint require Content-Type to be set to 'application/json'. While swagger does this implicitely, you have to create a workaround for programmatic HttpClients (e.g. in C#, I have to add an empty StringContent to the body).
Normally, get and delete requests, don't need a body or this type of header.

#### To reproduce

1. Use the app
2. Access GET/DELETE endpoints of the management API

#### Expected behavior

Content-Type headers are not necessary when there is no required request body

#### Actual behavior

Content-Type headers are enforced to be set

#### The command you used

N/A

#### A minimal project that can be used to reproduce the issue

N/A

#### Environment

- OS: Any
- Version: <=2.4.42
- Java version Any

#### Additional context

Reported by @JoeS-Bosch

**Comment by nagyesta** [comment]
Hi @JoeS-Bosch,
I think it should be fixed now. Please try with [v2.4.54](https://github.com/nagyesta/lowkey-vault/releases/tag/v2.4.54) and let me know how it went!
Thank you in advance!

**Comment by nagyesta** [comment]
Hi,
I assume, that this fix should resolve the original issue, so I am closing it. Please feel free to reopen in case it is still not working as intended!
Thank you again and best of luck!

**Comment by JoeS-Bosch** [comment]
Hi,
I was on vacation and could not check earlier.
I pulled the latest version (2.4.66) and the issue is fixed! Thanks for the quick response and action.

**Comment by nagyesta** [comment]
Hi,
thank you for letting me know! I am glad it works!
