### ISSUE TITLE
WWW-Authenticate resource parameter fails challenge verification even with custom hostname + SSL

### ISSUE THREAD

**Issue by craig0990** [nagyesta/lowkey-vault#1149]
#### Is your feature request related to a problem? Please describe.

I'm exploring the use of the Lowkey Vault at work, where we have an abstraction over the Key Vault client. The Lowkey Vault is great ( thank you ❤️ ) but it would be strongly preferable not to need the  `disableChallengeResourceVerification` parameter in Node.js.

I don't think it's possible to fix the challenge verificiation for normal use when running on localhost, but it could be possible to fix it when running in Docker with custom hostnames.

Currently, the WWW-Authenticate header returned by Lowkey uses the current request URI as the value of the `resource` parameter - e.g. with the default behaviour running on `localhost:8443`:

```
$ docker run -p 8443:8443 nagyesta/lowkey-vault:2.4.141
```

```
$ curl --silent -k -v https://localhost:8443/secrets/lorem 2>&1 | grep WWW
< WWW-Authenticate: Bearer resource="https://localhost:8443", authorization_uri="https://localhost:8443/secrets/lorem"
```

This would fail the challenge anyway, since the [Guidance for applications using the Key Vault libraries](https://devblogs.microsoft.com/azure-sdk/guidance-for-applications-using-the-key-vault-libraries/) says the "[...] host domain must match one of the known domain names [...]"

If we try it in Docker with a custom hostname:

```
$ docker network create --driver bridge lowkey-test
$ docker run --net=lowkey-test --hostname lowkey.vault.azure.net -p 8443:8443 nagyesta/lowkey-vault:2.4.141
```

```
$ docker run --net=lowkey-test --rm -it node:latest bash
> curl --silent -k -v https://lowkey.vault.azure.net:8443/secrets/lorem 2>&1 | grep WWW
< WWW-Authenticate: Bearer resource="https://lowkey.vault.azure.net:8443", authorization_uri="https://lowkey.vault.azure.net:8443/secrets/lorem"
```

We get the "full" hostname returned in the resource parameter. This doesn't match the challenge because the Key Vault client expects the requested URI to be a subdomain of the resource parameter - e.g. we'd have to request `myvault.lowkey.vault.azure.net` to pass the challenge, but we can't do that, because the `resource` parameter keeps matching our request URI.

I couldn't find this _directly_ spelled out, it's kind of implied in the linked [blog post](https://devblogs.microsoft.com/azure-sdk/guidance-for-applications-using-the-key-vault-libraries/#recommended-actions) where it says "[...] prepended with the “.” character to confirm a match [...]" and there's another hint in the [Basis-Theory/azure-keyvault-emulator source code](https://github.com/Basis-Theory/azure-keyvault-emulator/blob/49f6c870de5c0cdb9634b2dd90663ae07c0a495e/AzureKeyVaultEmulator/Startup.cs#L88)

#### Describe the solution you'd like

Support an additional `LOWKEY_*` argument (e.g. `LOWKEY_AUTH_RESOURCE`) to use in the WWW-Authenticate header `resource` parameter

#### Describe alternatives you've considered

It does work with `disableChallengeResourceVerification: true`, but it would reduce the need to add changes, conditionals, or risk by exposing that option to users, if we didn't need to use it in the first place.

#### Additional context

Rather than ask for a feature request without putting any effort in, I've made an attempt at making this work in a personal fork:

craig0990/lowkey-vault@ae7f1068fffc06a1257e5b4795b81869d05bb36e

I'm not really a Java dev 🥲 I've copied the approach used in the `VaultImporterProperties.java` class to add `@Value` usage in the constructor of the `CommonAuthHeaderFilter` where the header is constructed.

I didn't know how to make the `@Value` injection keep the current behaviour by default, since the current behaviour is dynamic to the received request hostname. I guess you could default to blank/null and add a conditional in the constructor, if that's an issue? But I'm assuming that if the user isn't running Lowkey with a custom hostname, they're probably going to run with `disableChallengeResourceVerification` and not particularly care what's in the `resource` parameter. Maybe that's a poor assumption.

I've attempted test cases, but again, I'm sure they could be improved.

I've also forked the Node.js example repository, to give an example of running the existing Node tests using the new `LOWKEY_AUTH_RESOURCE` argument:

https://github.com/craig0990/lowkey-vault-example-nodejs

I'll raise a PR after submitting this issue, if only for reference - I can understand if there's a different/better approach to be taken.

**Edit:** PR at #1150

**Comment by nagyesta** [comment]
Hi @craig0990 ,
first of all, thank you! I am not getting feature requests often and especially not with a PR :). 

I like your solution and will use it. Added a single commit on top of it and pushed to my fork to allow the pipeline to run successfully (unfortunately there are some secrets which are needed for a green build). As a result the new PR will be #1151 and I will close #1150 without merging since it is no longer needed.

I hope this is not an issue for you!

**Comment by nagyesta** [comment]
The release completed, you can use it with `v2.5.0`.

Thank you again and best of luck!

**Comment by craig0990** [comment]
That's absolutely awesome @nagyesta - that's the last missing piece to help us on our test journey, so thanks for building such a solid local emulator 🙏🏻

**Comment by nagyesta** [comment]
Thank you!
