### ISSUE TITLE
URLs should be case-insensitive

### ISSUE THREAD

**Issue by tomachristian** [nagyesta/lowkey-vault#1158]
#### Describe the bug

Using the official KeyVault .NET library for working with LowKey Vault, I noticed that the `unwrapKey` and `wrapKey` endpoints were not working with the library. Investigating this further I noticed that Lowkey Vault is using lower-case paths for its controller mappings... and that they are case-sensitive, so the requests from the official .NET library do not work, because those use `unwrapKey` instead of `unwrapkey`.

#### Workaround

For anyone still wanting to use this, you can create a `DelegatingHandler` that you place in the processing pipeline that will lowercase the path that the .NET official library uses. You can get the gist of it from here

```
private sealed class BugFixHandler : DelegatingHandler
{
    protected override HttpResponseMessage Send(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        if (request.RequestUri is not null && request.RequestUri.AbsolutePath.EndsWith("Key"))
        {
            var builder = new UriBuilder(request.RequestUri);

            // We need to lowercase only the 'Key' suffix at the end
            builder.Path = builder.Path[..^3] + "key";

            request.RequestUri = builder.Uri;
        }

        return base.Send(request, cancellationToken);
    }
}
```

_This will not work for all endpoints, you need to tailor the workaround for your own needs._

**Comment by nagyesta** [comment]
Thank you for your feedback! I am glad it is useful! Fix this issue, please try it with [v2.5.6](https://github.com/nagyesta/lowkey-vault/releases/tag/v2.5.6) and let me know whether it solved your problem!

Thank you in advance!

**Comment by tomachristian** [comment]
I can confirm that the latest version no longer has the problem. Thank you!

**Comment by nagyesta** [comment]
Thank you!
