### ISSUE TITLE
Wrong type for jacksom-bom dependency in lowkey-vault-client 

### ISSUE THREAD

**Issue by espenaf** [nagyesta/lowkey-vault#258]
#### Describe the bug

Dependency on jacksom-bom in lowkey-vault-client needs to specify <type>pom</type>. If not the it will try to resolve the default type which is jar.

#### To reproduce

1. Add lowkey-vault-client as a dependency in a Maven project where jackson-bom is already used
2. Maven fails with `Could not resolve dependencies for project my.project:module:jar:1.0-SNAPSHOT: Could not find artifact com.fasterxml.jackson:jackson-bom:jar:2.13.3`

#### Expected behavior

That the build works by downloading the pom instead

#### Actual behavior

Maven fails with `Could not resolve dependencies for project my.project:module:jar:1.0-SNAPSHOT: Could not find artifact com.fasterxml.jackson:jackson-bom:jar:2.13.3`

#### The command you used

mvn clean install

#### A minimal project that can be used to reproduce the issue

If applicable. Please do NOT share sensitive information.

#### Environment

- OS: Mac OS 12.5
- Version: 1.8.36
- Java version: 11.0.16

#### Additional context

Temporarly fixed with

        <dependency>
            <groupId>com.github.nagyesta.lowkey-vault</groupId>
            <artifactId>lowkey-vault-client</artifactId>
            <version>1.8.35</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>com.fasterxml.jackson</groupId>
                    <artifactId>jackson-bom</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by nagyesta** [comment]
Hi @espenaf ,
sorry to hear about this issue, thank you for giving Lowkey Vault a chance and for reporting the bug!

You are right, the generated POM I have shipped is incorrect. I will take a look (hopefully today) and fix it. The temporary fix you have used should be fine in the meantime, thank you for sharing it with the community!

**Comment by nagyesta** [comment]
Hi @espenaf ,
just released `v1.10.0` it should do the trick. Please let me know in case it didn't! Thank you!
