### ISSUE TITLE
Add support for alias vault URLs

### ISSUE THREAD

**Issue by nagyesta** [nagyesta/lowkey-vault#298]
From: @aiceball

One issue I do have, however, is that to my understanding the vault is defined ONLY through the keyvault URI used. If I have a container on the same docker network communicating with lowkey-vault, the vault I'll be hitting will be based on the internal network name I gave that container, i.e. `akv`. If I try to write content to the lowkey-vault from a local python-client, however, the address is different, because I am communicating with lowkey-vault from outside the docker network:
```mermaid
graph
    Python-client -- https://localhost:8443 --> Docker-Lowkey-Vault
    Docker-Service -- https://akv:8443 --> Docker-Lowkey-Vault
```

I wonder if some sort of vault aliasing feature can be added on the management API layer, either at creation time:
```bash
POST /management/vault

{
  "baseUri": "https://bbv:8443",
  "aliasUri": "https://localhost:8443",
  "recoveryLevel": "CustomizedRecoverable+Purgeable",
  "recoverableDays": 42,
  "created": 1641092645,
  "deleted": 1641092645
}
```

or an additional modification point:

```bash
PUT /management/vault/{baseUri}

{
 "aliasUri": "https://{newUri}:8443"
}
```

What this would enable is an access to the same keyvault from multiple networks, i.e. a local network, an internal docker network, an ngrok tunnel, etc.

I am using the Azure Python library to communicate with the Lowkey-Vault if that information is relevant.

**Comment by nagyesta** [comment]
**Notes**
- Add aliases to the vault objects
- Change vault resolution logic to use either the vault URI or one of the aliases (make sure aliases are unique as well)
- Create filter for replacing vault URI in the entity Ids returned by Lowkey Vault (limitation: won't work in Base64 strings)
- Add aliases field in import/export
- Add new management endpoints to define/edit/remove aliases for a vault
- Add tests

**Comment by nagyesta** [comment]
Hi @aiceball,
just managed to release this feature in `v1.13.0` please try it out and let me know whether it solved your issue!
Thank you in advance!

**Comment by aiceball** [comment]
Hello @nagyesta,

I have tried the feature and it works with the case exactly!
Appending an alias with docker network name to the default keyvault `localhost:8443` works exactly as intended.
My client container is able to read the secrets provided from outside by calling the alias name.

Thank you very much for this feature, it's a huge boon for testing!

**Comment by nagyesta** [comment]
Great, thank you for letting me know @aiceball ! Closing the ticket.
