### ISSUE TITLE
Add M1 Mac support using ARM Docker image

### ISSUE THREAD

**Issue by nagyesta** [nagyesta/lowkey-vault#343]
From: @conblem

> We are using lowkey-vault for local testing of our .netcore api's. Some of our devs use M1 MacBooks and docker has to resort back to amd64 emulation on these devices, because there are no native images. The startup time of our whole stack depends on first having a running lowkey-vault instance. At the moment this is really slow for our engineers using ARM machines. We would really appreciate a ARM build of your project.

**Comment by conblem** [comment]
Thanks for creating this issue. First off really appreciate the project. Docker natively supports building multi arch images using buildx. The whole topic is documented here: [https://docs.docker.com/build/building/multi-platform/](https://docs.docker.com/build/building/multi-platform/) . The eclipse temurin images does seem to have builds for arm you can see this referenced here: [https://hub.docker.com/_/eclipse-temurin](https://hub.docker.com/_/eclipse-temurin)

**Comment by nagyesta** [comment]
Hi @conblem
thank you! I have started to look into this. It is not that easy to make this part of my build pipeline as:
1. the Gradle plugin I am using does not support buildx yet
2. The base image is not the same (the Alpine based JRE image does not appear to have an arm64 variant) and I would love to keep the version pinned with the SHA as well
3. I will need to figure out how to build it on Github as well.
 
Anyway, I have managed to build an experimental version locally (although I couldn't figure out how to test it) using this Dockerfile:

```Dockerfile
FROM eclipse-temurin:11.0.17_8-jre-jammy@sha256:aa4584a9a4a59653192d854382049b4c8e028c7c62710344c0beeb30ffdb4314
LABEL maintainer="nagyesta@gmail.com"
EXPOSE 8443:8443
ADD lowkey-vault.jar /lowkey-vault.jar
RUN mkdir "/import"
CMD [ "sh", "-c", "ls /" ]
ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar /lowkey-vault.jar ${LOWKEY_ARGS}"]
```
If you wish to give it a try, please check it out here: https://hub.docker.com/layers/nagyesta/lowkey-vault-experiment/1.13.23_arm64/images/sha256-11d5b470679e7beca3f4702aa707401deea5616bd9bfb85a004fb9a374aae182?context=repo

I will continue the work to figure out how I can solve this on the long run, maybe I could set up a different project that would just grab the latest jar and build the arm image and tag it using a different tag name (e.g. 1.13.23_arm64 or similar).

Do you think this could work or would you need the same tag name with different architectures?

Thank you in advance!

**Comment by conblem** [comment]
Hello thanks for the effort the manually built image works 🎊 . As far as I can see the [Docker Plugin](https://github.com/palantir/gradle-docker) supports buildx and different platforms: 
<img width="852" alt="grafik" src="https://user-images.githubusercontent.com/19853857/201954842-b8f33315-7ab3-4f59-bfba-2e30715657fb.png">

**Comment by nagyesta** [comment]
Hi @conblem 
Thank you for testing the image and thank you for pointing out the buildx support in the plugin! I have reached the wrong conclusion based on the changelog here: https://github.com/palantir/gradle-docker/tree/develop/changelog/@unreleased

In the meantime I have found a Github action too, that should be able to set up buildx for the build: https://github.com/marketplace/actions/docker-setup-buildx

I will spend some time on this and figure out how to integrate everything and have automatic builds for every platform.

**Comment by nagyesta** [comment]
Hi @conblem ,
I have ended up creating a new repository for these non-AMD64 images and managed to push the first two to the main Docker repo:
https://hub.docker.com/layers/nagyesta/lowkey-vault/1.13.23-arm/images/sha256-8868d257f0e16c937565d23332cffb4aa4f77a4cb92e755eeef650371335c438?context=repo
https://hub.docker.com/layers/nagyesta/lowkey-vault/1.13.23-arm64/images/sha256-36fb72a4d2410ef7dda10ca286703fac41ed35aa302f59848d7b208766ca3d3b?context=repo

Please feel free to use them, I will make sure to trigger a build for these after every Lowkey Vault release.

Looking forward to your feedback on how it works, thank you!

**Comment by conblem** [comment]
Hello this is a very welcome change thanks for the effort!

I have not been able to test the new images but will do that soon :)
Is there a particular reason you have choosen to use different tags? For us this causes some akward hacks in our codebase. We use a shared docker-compose file for all our developers. Docker then just pulls the correct image arch based on the system. Now we would have to override this for all our developers using M1 devices to use the new arm64 tags you have setup. This is not a huge hassle however and just having native images is already a huge improvement, thanks alot!

**Comment by nagyesta** [comment]
Hi @conblem and @irby ,
I have some good news! Finally had some time to look into this a bit better. Just released the new image that should just do the trick. Please find it here: https://hub.docker.com/layers/nagyesta/lowkey-vault/1.13.33-jammy/images/sha256-c2a85999fb172a2fde4570e80f891d90372500fb0daf79c35f749d41851e3bb7?context=repo

I have decided to keep the suffix of the base image I am using in this case as users will be able to select between the original, Alpine, variant and the multi-arch variant based on their needs (smaller image vs. more convenience in case of a mixed setup).

The amd64 version will be always tested using the Docker example project, so the chance of having a broken image for the arm64 and arm/v7 variants should be minimal, but should you ever face an issue with it, feel free to open a bug.

Thank you again for your feedback and patience!
