### ISSUE TITLE
Unable to find active vault when launching Lowkey Vault from a "sibling" container

### ISSUE THREAD

**Issue by nagyesta** [nagyesta/lowkey-vault#509]
> For my usecase I am launching LowKeyVault from with another container (making LowKeyVault as "sibling" container) and I need to be able to connect to it. The IP address is automatically assigned by docker engine, in my case typically `172.17.0.x`. The environment is dev machine and CI (so no K8S involved anywhere).
> 
> Thus the error message I get is `Unable to find active vault: https://172.17.0.3:8443`.
> 
> Any suggestions on what I can do here?

_Originally posted by @damianh in https://github.com/nagyesta/lowkey-vault/issues/256#issuecomment-1472835740_

**Comment by nagyesta** [comment]
Hi @damianh ,
Thank you for using Lowkey Vault and sharing your use-case! I will try to figure this out with you!
If I understood correctly, both your application and Lowkey Vault are running in a container and they are siblings similarly to what the diagram shows below:

```mermaid
  C4Deployment
    Deployment_Node(context, "Host", "127.0.0.1", "Your dev/CI machine."){
        System(tests, "Tests", "127.0.0.1")
        Container(sut, "System under test", "App being tested", "https://172.17.0.x:8443/")
        Container(lv, "Lowkey Vault", "AKV test double", "https://172.17.0.y:8443/")
    }

    Rel(tests, sut, "Makes test calls", "HTTPS")
    Rel(sut, lv, "Uses Vault", "HTTPS")
    Rel(tests, lv, "Sets up Vault content", "HTTPS")
    
    UpdateLayoutConfig($c4ShapeInRow="2", $c4BoundaryInRow="1")
```
 
If this is the case, then I think the connection between the application and Lowkey Vault could even use Docker to assign a suitable host name for us using [--add-host](https://docs.docker.com/engine/reference/commandline/run/#add-host). AFAIK it will add the name of the container as host name automatically, allowing your other containers to access it using that, but it does not need to be the name of your container necessarily. If you could add an extra host to your application container using any of the supported certificate names listed [here](https://github.com/nagyesta/lowkey-vault/blob/8e296d62b33e6a752e7651e1971eff0f80e11a2c/lowkey-vault-app/build.gradle#LL74-L74) and register that vault either as a [vault](https://github.com/nagyesta/lowkey-vault/tree/8e296d62b33e6a752e7651e1971eff0f80e11a2c/lowkey-vault-app#non-default-vaults) or as an [alias](https://github.com/nagyesta/lowkey-vault/tree/8e296d62b33e6a752e7651e1971eff0f80e11a2c/lowkey-vault-app#defining-vault-aliases-for-auto-registered-vaults), then your application should be able to access Lowkey Vault.

I think using the default vault, ```https://localhost:8443``` and registering an alias for it with the name: ```https://lowkey-vault.local:8443``` would be probably what you need, so you could try adding: ```--LOWKEY_VAULT_ALIASES="localhost=lowkey-vault.local:8443"``` to your startup arguments.

This way you should be able to connect using ```https://localhost:8443``` from localhost (your tests or any code initializing vault content) and your application can use ```https://lowkey-vault.local:8443``` instead of the generated IP. 

Do you think that could work?

P.S. If the default port is already used, you can simply [select another](https://github.com/nagyesta/lowkey-vault/tree/8e296d62b33e6a752e7651e1971eff0f80e11a2c/lowkey-vault-app#custom-port-use) an use that.

**Comment by damianh** [comment]
Hi @nagyesta , thanks for the fast response. 

That diagram is a good representation and a valid use case. I have a minor difference is that the tests are being run in same container as your `system under test` box and I'm launching the sibling container from there (as part of a test fixture).
![image](https://user-images.githubusercontent.com/57436/225844881-96af2daf-d7d5-424c-9bfc-48a800042642.png)

However, this doesn't really make a difference.

I'm going to give your suggestion a try. Am going to be AFK for few days and will get back to you early next week. 

Cheers!

**Comment by nagyesta** [comment]
Hi @damianh , sounds great, best of luck!

**Comment by nagyesta** [comment]
Hi @damianh ,
I don't want to be impatient or anything, just wanted to make sure you are not stuck in case my recommendation did not work out for some reason. Please let me know if you need assistance!

**Comment by damianh** [comment]
Managed to get the aliases working!

Cheers :)

**Comment by nagyesta** [comment]
Great news! Glad it worked out! Closing the ticket... Please feel free to open a new one in case of issues!
