### ISSUE TITLE
How to use a "trusting" HttpClient with LowKeyVault

### ISSUE THREAD

**Issue by paullatzelsperger** [nagyesta/lowkey-vault#570]
#### Question

As you know, the Azure KeyVault's `SecretClient` mandates the use of `https://` urls for the vault instance. 
Unfortunately it also uses a customized version of the Netty `HttpClient`, which makes it harder to engage a ["trust-all" SSL configuration](https://stackoverflow.com/a/2893932).

You do mention [in the wiki](https://github.com/nagyesta/lowkey-vault/wiki/Example:-How-can-you-use-Lowkey-Vault-in-your-tests#3-connecting-using-https) that the enclosed SSL cert must be trusted, but do not give an example of how this would be done.

To that end, listing the concrete [keytool command](https://docs.oracle.com/javase/tutorial/security/toolsign/step5.html) showing in particular the alias and password for the enclosed JKS would be very helpful. For example:
```bash
 keytool -export -keystore cert.jks -alias <?????> -file Example.cer
```

Then, once the `*.cer` is created, it would round things up nicely to show (or link) how to import the certificate on the host OS (win, macos, linux).

**Comment by nagyesta** [comment]
Hi @paullatzelsperger ,
first of all, thank you for giving Lowkey Vault a chance, and especially taking the time to raise this issue! I will try to help you with your issue. From what you have shared, I understand that you are using the Java client in your application. In this case, you can try the following options:

### Option 1: Use the provided P12 as a trust store

I am using this option in the [Lowkey Vault Java Example](https://github.com/nagyesta/lowkey-vault-example). The following System properties need to be supplied to the application as it is done [here](https://github.com/nagyesta/lowkey-vault-example/blob/9e6db4b35835c25b4eacea4aa1eed25a3544147f/build.gradle#L54-L56). It should work just fine when using the [default HTTP client](https://github.com/nagyesta/lowkey-vault-example/blob/main/src/main/java/com/github/nagyesta/lowkeyvault/example/AzureAccessConfiguration.java#L41).

### Option 2: Use your own certificate

You are not alone with the SSL problem, other users reported this as well. As a result, Lowkey Vault has [support for using your own certificate](https://github.com/nagyesta/lowkey-vault/wiki/Example:-Using-a-custom-certificate-with-Lowkey-Vault) (which can be either a perfectly valid certificate from a well-known CA, or you can even generate your own to self-signed certificate and make that trusted. For generating your own certificate, you can look for inspiration [here](https://github.com/nagyesta/lowkey-vault/blob/16318c215bac5f8b08b64d702ddbe7984b148a9b/lowkey-vault-app/build.gradle#L57-L109) to see how the Lowkey Vault certificate was generated.

### Option 3: Use the Lowkey Vault Client for your local/CI runs

The [Lowkey Vault Client](https://github.com/nagyesta/lowkey-vault/tree/main/lowkey-vault-client#usage) was created to allow easy bypass of the SSL config as well. I am using this client in the tests both in case of the Testcontainers module (for example [here](https://github.com/nagyesta/lowkey-vault/blob/16318c215bac5f8b08b64d702ddbe7984b148a9b/lowkey-vault-testcontainers/src/test/java/com/github/nagyesta/lowkeyvault/testcontainers/LowkeyVaultContainerJupiterTest.java#L36-L48)) and in case of the Docker module taking care of all end-to-end testing effort as seen for example [here](https://github.com/nagyesta/lowkey-vault/blob/16318c215bac5f8b08b64d702ddbe7984b148a9b/lowkey-vault-docker/src/test/java/com/github/nagyesta/lowkeyvault/parallel/RunParallelCucumberTest.java#L34-L39). It is important to note, that the Lowkey Vault Client is NOT intended to be used in production, please make sure to only use it in local/CI runs...

Do you think any of these options could help you resolve the issue you are facing?

**Comment by paullatzelsperger** [comment]
@nagyesta thanks for your timely reply. Maybe clearing up the background will clarify things further:

We have a Helm chart, that contains an application, which depends on an Azure Keyvault upon startup. In our CI we want to do a smoke test, which essentially consists of installing the chart, and verifying that it boots up fine.

For that test I cannot (and don't want to) modify the application code base or the chart, which basically leaves me with two options:
1. use a self-signed certificate, add that to the application pod's truststore, and use that cert for LowKey or
2. use an _actual_ Azure Keyvault instance

So, short of baking a customizable startup command into the Docker image and the Helm chart, which allows for adding the self-signed cert to the trusted list (something similar to [this](https://stackoverflow.com/a/67232164)), I don't see how I would achieve that. 

Do you have an idea?

**Comment by nagyesta** [comment]
Hi @paullatzelsperger ,
Thank you for the additional details, it makes a lot more sense now! My first reaction would be, that the cert you mentioned here doesn't have to be self-signed:

> 1. use a self-signed certificate, add that to the application pod's truststore, and use that cert for LowKey or

You can even use a real certificate from a real CA, like Let's Encrypt. Or in case your organisation is already using their own root certificate for HTTPS access between your services, then assuming that the root certificate is already added to the trust store of your application, you could generate a certificate using the root and use that for Lowkey Vault. This way your app would trust the root cert, as well as the one you generated for Lowkey Vault.

I don't really see nicer solutions yet, but I will keep thinking. Please let me know if this gets you closer to the solution!

Thank you!

**Comment by nagyesta** [comment]
Hi @paullatzelsperger , 

closing as there were no new ideas from either of us, and unfortunately I think the constraints you have outlined make it impossible to you use Lowkey Vault at this time. 

Please feel free to reopen this issue if the situation changes! Best of luck with the issue you are facing!
