### ISSUE TITLE
Add basic support for 7.4 API version

### ISSUE THREAD

**Issue by nagyesta** [nagyesta/lowkey-vault#697]
Done criteria

- [x] New controllers added to support v7.4 API endpoints using the same functionality as in case of v7.3
- [x] New test cases added
  - [x] UT/IT
  - [x] End-to-end
- [x] Documentation updated
  - [x] Readme
  - [x] Wiki
- [x] Examples updated to use latest API

**Comment by nagyesta** [comment]
Hi @abtris ,
As you have reported a related issue (https://github.com/nagyesta/lowkey-vault-example-go/issues/100) I wanted to ask how urgent is this for you?

**Comment by abtris** [comment]
No urgent, I can still use older version.

**Comment by nagyesta** [comment]
Hi @abtris ,
the changes were released in v2.1.0. Please let me know whether it solved your original issue (either here or on https://github.com/nagyesta/lowkey-vault-example-go/issues/100)...

Thank you!

**Comment by nagyesta** [comment]
Hi,
I assume this is resolved, so I am closing the issue. Please feel free to reopen or create a new issue in case it is not.
Thank you!
