### ISSUE TITLE
Stopping the container seems to take longer than necessary

### ISSUE THREAD

**Issue by nagyesta** [nagyesta/lowkey-vault#806]
### Discussed in https://github.com/nagyesta/lowkey-vault/discussions/805

<div type='discussions-op-text'>

<sup>Originally posted by **damianh** December 14, 2023</sup>
Hi there, lovely tool!

Not sure if this can be classified as an issue or not, however it seems to take 10+ seconds to stop the container. As a test dummy, I would somewhat expect that startup and shutdown to be snappy.

`docker run --rm -d --name lowkey nagyesta/lowkey-vault:2.1.26-jammy` -> ~1 second
`docker stop lowkey` -> 10+ seconds

Cheers :) </div>

**Comment by nagyesta** [comment]
FYI @damianh

**Comment by nagyesta** [comment]
Something must be with the multiarch image, because the original image is behaving as expected:

Multiarch image shutdown (Kubuntu amd64 host), 11 seconds
```
$ date && docker run --rm -d --name lowkey nagyesta/lowkey-vault:2.1.26-jammy && date
2023. dec. 14., csütörtök, 21:29:40 CET
2bf2529ac686fb2635dea0dd43fc6657dc75065b655a056dcee163181d467ca5
2023. dec. 14., csütörtök, 21:29:40 CET
$ date && docker stop lowkey && date
2023. dec. 14., csütörtök, 21:29:44 CET
lowkey
2023. dec. 14., csütörtök, 21:29:55 CET
```

Original image shutdown (Kubuntu amd64 host), 2 seconds
```
$ date && docker run --rm -d --name lowkey nagyesta/lowkey-vault:2.1.26 && date
2023. dec. 14., csütörtök, 21:30:03 CET
338963d2300556905e410f2bb1bc985943a8f90c247f1b6562950f8423430f6c
2023. dec. 14., csütörtök, 21:30:03 CET
$ date && docker stop lowkey && date
2023. dec. 14., csütörtök, 21:30:06 CET
lowkey
2023. dec. 14., csütörtök, 21:30:08 CET
$ 
```

**Comment by nagyesta** [comment]
Swapping base image to ```eclipse-temurin:17.0.9_9-jre-ubi9-minimal``` appears to be promising, although it would mean, that we need to drop arm/v7 support. I will think about it a bit.

**Comment by nagyesta** [comment]
Hi @damianh,
I have just released a fixed version. According to my tests, these will stop faster (1-2 seconds). Please feel free to try this tag:  [2.1.99-ubi9-minimal](https://hub.docker.com/layers/nagyesta/lowkey-vault/2.1.99-ubi9-minimal/images/sha256-3163b427675c2d4319f857ee3b107e4aff040f578a9230d906b02821492ff6dc?context=explore) and let me know how it worked!

Thank you in advance!

**Comment by damianh** [comment]
Tried the new image and confirm that is stops as expected now. Thanks for addressing!

**Comment by nagyesta** [comment]
Hi, thank you for letting me know!
