### ISSUE TITLE
SecretClient doesn't seem to be retrieving managed secrets

### ISSUE THREAD

**Issue by mcolebiltd** [nagyesta/lowkey-vault#827]
I noticed that when creating a certificate in Azure Key Vault, a new secret is automagically created to correspond to the certificate. In lowkey-vault, after adding a new certificate, I am able to retrieve the secret immediately using `secretClient.GetSecret(certificateName)`, but when retrieving the list of all secrets `secretClient.GetPropertiesOfSecrets().ToList()`, the result does not contain the secret with the certificate name. It -does- appear to work correctly when targeting an actual Azure Key Vault, so it seem perhaps it's an issue with lowkey-vault? I am opening a PR with a broken test.

**Comment by nagyesta** [comment]
No problem @mcolebiltd , I know one :)

I have confirmed, that it is in fact listing the secrets with the Java client as well:

```java
// list already generated secrets managed by certificates
DefaultAzureCredential credentials = new DefaultAzureCredentialBuilder().build();
SecretClient secretClient = new SecretClientBuilder().vaultUrl(REAL_KEY_VAULT_URL)
        .credential(credentials)
        .buildClient();

List<SecretProperties> result = secretClient.listPropertiesOfSecrets().stream().collect(Collectors.toList());

result.stream().forEach(secret -> System.out.println(secret.getName() + " - " + secret.isManaged()));
```

printing:

```
disabled - null
disabled-2 - null
ec-p256 - true
ec-p256k - true
ec-p384 - true
ec-p521 - true
lowkey-vault-imported - true
plain-text - null
rsa2048 - true
rsa3072 - true
rsa4096 - true
secret - null
```

Based on this, I will consider this as a bug and try to fix it.

**Comment by nagyesta** [comment]
The same is true for keys as well:

```java
// list already generated keys managed by certificates
DefaultAzureCredential credentials = new DefaultAzureCredentialBuilder().build();
KeyClient keyClient = new KeyClientBuilder().vaultUrl(REAL_KEY_VAULT_URL)
        .credential(credentials)
        .buildClient();

List<KeyProperties> result = keyClient.listPropertiesOfKeys().stream().collect(Collectors.toList());

result.stream().forEach(key -> System.out.println(key.getName() + " - " + key.isManaged()));
```

Listing:

```
disabled - null
ec-p256 - true
ec-p256k - true
ec-p384 - true
ec-p521 - true
lowkey-vault-imported - true
rsa2048 - true
rsa3072 - true
rsa4096 - true
```

**Comment by nagyesta** [comment]
Confirmed with Get Key Versions as well.

**Comment by nagyesta** [comment]
Hi @mcolebiltd ,
I have just released [v2.2.0](https://github.com/nagyesta/lowkey-vault/releases/tag/v2.2.0) which should fix it. 
Please feel free to try it, and let me know whether it is working for you too!

P.S. Reopening the ticket to show that it is still not 100% confirmed. I shouldn't have added the keyword to the commit message.

**Comment by mcolebiltd** [comment]
@nagyesta Confirmed, this works for me. Thanks for the quick fix!

**Comment by nagyesta** [comment]
Thank you for confirming!
