### ISSUE TITLE
Basic 7.5 API support

### ISSUE THREAD

**Issue by nagyesta** [nagyesta/lowkey-vault#873]
### Done criteria

- [x] 7.5 API variants are added for each controller
- [x] New test cases added using the new API
- [x] Documentation updated

**Comment by nagyesta** [comment]
On hold until the new Java SDK adds support to the 7.5 API

**Comment by darktohka** [comment]
Since @azure/keyvault-secrets version 4.8.0 (JavaScript/Node API) now expects 7.5 API by default, this should be added as soon as possible. Currently @azure/keyvault-secrets version 4.8.0 returns RestError 400

**Comment by nagyesta** [comment]
Hi @darktohka ,

thank you, I agree, this should be merged as fast as possible! Especially, because the Go SDK does not even allow overrides, so the default 7.5 API version is the only one available in their case. Unfortunately, the Java SDK which my tests are using is not updated yet, so I cannot make my own tests green unless I decide to not test the new API endpoints at all. As I don't like the idea of releasing untested code, I would like to wait for the Java SDK release.

In the meantime, please consider overriding the API version in the JS client when you are running your tests. You can do so like this: https://github.com/nagyesta/lowkey-vault-example-nodejs/blob/6038ac5503f8d56ec2901e6e979a67f744115058/test/index.test.js#L56

Do you think this workaround could be a valid short term compromise?

**Comment by nagyesta** [comment]
We are in luck, the SDK PRs arrived today, the release is in progress. This will be included in `2.3.0`.
