### ISSUE TITLE
NullPointerException when importing a certificate without critical extensions

### ISSUE THREAD

**Issue by alex-cote** [nagyesta/lowkey-vault#930]
#### Describe the bug

A NullPointerException occurs when importing a certificate that has no critical extensions. The certificate was in PFX format.

#### To reproduce

1. Import a PFX certificate without extensions using the API (_POST https://localhost:8443/certificates/:certificate-name/import?api-version=7.5_).

#### Expected behavior

Certificate should be imported into the vault.

#### Actual behavior

Got the following 500 error:
```json
{
    "error": {
        "code": "com.github.nagyesta.lowkeyvault.service.exception.CryptoException",
        "innererror": {
            "code": "java.lang.NullPointerException",
            "message": "Cannot invoke \"java.util.Set.contains(Object)\" because the return value of \"java.security.cert.X509Certificate.getCriticalExtensionOIDs()\" is null"
        },
        "message": "Failed to generate CSR for certificate with name: test"
    }
}
```

#### Environment

- OS: Windows
- Version: 2.3.13

#### Additional context

As mentioned in the documentation, method [getCriticalExtensionOIDs()](https://help.intrexx.com/apidocs/jdk17/api/java.base/java/security/cert/X509Extension.html#getCriticalExtensionOIDs()) may returns null which looks to be the actual case in this scenario.

> Returns:
>     a Set (or an empty Set if none are marked critical) of the extension OID strings for extensions that are marked critical. **If there are no extensions present at all, then this method returns null.** 
 
Here is the stack trace:
> 2024-04-03 12:41:25 16:41:25.051 DEBUG [io-8443-exec-10] o.s.w.f.CommonsRequestLoggingFilter      : Before request [POST /certificates/test/import?api-version=7.5, client=172.22.0.1]
> 2024-04-03 12:41:25 16:41:25.058  INFO [io-8443-exec-10] c.g.n.l.c.c.CommonCertificateController  : Received request to https://localhost:8443 import certificate: test using API version: 7.5
> 2024-04-03 12:41:25 16:41:25.072 ERROR [io-8443-exec-10] c.g.n.l.c.ErrorHandlingAwareController   : Returning error model due to exception.
> 2024-04-03 12:41:25 com.github.nagyesta.lowkeyvault.service.exception.CryptoException: Failed to generate CSR for certificate with name: test
> 2024-04-03 12:41:25     at com.github.nagyesta.lowkeyvault.service.certificate.impl.CertificateGenerator.generateCertificateSigningRequest(CertificateGenerator.java:92)
> 2024-04-03 12:41:25     at com.github.nagyesta.lowkeyvault.service.certificate.impl.KeyVaultCertificateEntity.<init>(KeyVaultCertificateEntity.java:110)
> 2024-04-03 12:41:25     at com.github.nagyesta.lowkeyvault.service.certificate.impl.CertificateVaultFakeImpl.importCertificateVersion(CertificateVaultFakeImpl.java:55)
> 2024-04-03 12:41:25     at com.github.nagyesta.lowkeyvault.controller.common.util.CertificateRequestMapperUtil.importCertificateWithAttributes(CertificateRequestMapperUtil.java:43)
> 2024-04-03 12:41:25     at com.github.nagyesta.lowkeyvault.controller.common.CommonCertificateController.importCertificate(CommonCertificateController.java:75)
> 2024-04-03 12:41:25 Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Set.contains(Object)" because the return value of "java.security.cert.X509Certificate.getCriticalExtensionOIDs()" is null
> 2024-04-03 12:41:25     at com.github.nagyesta.lowkeyvault.service.certificate.impl.CertificateGenerator.addAttributeBasedOnCertificate(CertificateGenerator.java:211)
> 2024-04-03 12:41:25     at com.github.nagyesta.lowkeyvault.service.certificate.impl.CertificateGenerator.lambda$generateCertificateSigningRequest$0(CertificateGenerator.java:88)
> 2024-04-03 12:41:25     at java.base/java.util.stream.SpinedBuffer$1Splitr.forEachRemaining(Unknown Source)
> 2024-04-03 12:41:25     at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
> 2024-04-03 12:41:25     at com.github.nagyesta.lowkeyvault.service.certificate.impl.CertificateGenerator.generateCertificateSigningRequest(CertificateGenerator.java:88)

**Comment by nagyesta** [comment]
Hi @alex-cote ,
thank you for reporting this bug, and thank you for using Lowkey Vault! I am sorry to hear that it is causing an issue and will look into it as soon as I can!

**Comment by nagyesta** [comment]
Hi @alex-cote ,
could you please try it with [v2.3.41](https://github.com/nagyesta/lowkey-vault/releases/tag/v2.3.41)?

I am not that familiar with certificates, so I am not 100% that it will solve everything, but at least the import worked with my generated example certificate.

Please let me know how it goes, I am happy to look into it further if it is still not okay...

Thank you and best of luck!
