### ISSUE TITLE
Assumed Identity endpoint in Lowkey Vault

### ISSUE THREAD

**Issue by alpapad01** [nagyesta/lowkey-vault#960]
Fist, great project, solves a tone of problems.  A big thank-you!!

#### Is your feature request related to a problem? Please describe.
To test an application which uses Azure vault, without changing configurations (and possibly code?), one needs to have the  nagyesta/assumed-identity:1.2.16 docker image running next to lowkey-vault. 

#### Describe the solution you'd like

It would be great to expose the single GET endpoint of assumed-identity from lowkey-vault itself. This way, there is one container less to run (less resources).

I have tested such a solution and it works.

**Comment by nagyesta** [comment]
Hi @alpapad01 ,
this was implemented and is being released in [v2.4.2](https://github.com/nagyesta/lowkey-vault/releases/tag/v2.4.2).

I think it should be working, but please let me know whether it is what you had in mind!

Thank you in advance!

**Comment by nagyesta** [comment]
Hi @alpapad01 ,
I assume it must have worked, so I am closing the ticket. Please feel free to reopen (or open a new one) in case you see further problems!

Thank you and best of luck!
