### ISSUE TITLE
CommonAuthHeaderFilter should exclude /actuator/**

### ISSUE THREAD

**Issue by alpapad01** [nagyesta/lowkey-vault#966]
#### Describe the bug

When trying to use the SB actuator, the CommonAuthHeaderFilter  blocks it. In the logs we get:

`c.g.n.l.filter.CommonAuthHeaderFilter    : Sending token to client without processing payload: /actuator/health/readines
`
#### To reproduce

curl https://${host}:${port} /actuator/health/readines

#### Additional context

The actuator is used in docker-compose to verify that the vault has started so queries can be send

**Comment by nagyesta** [comment]
Hi @alpapad01 ,
thank you, I will look into this and fix it as soon as I can!

**Comment by nagyesta** [comment]
Hi @alpapad01 ,
finally I had some time to check this properly, sorry for the delay in my response!

I am pretty sure, that the actuator endpoint you are looking for is not active in this project, so I can only propose to please try using the `/ping` endpoint instead for liveness and readiness checks.

Would this proposed endpoint solve your issue, or are you looking for some more details from the container?

**Comment by alpapad01** [comment]
Yes, you are right, there is no actuator. Using ping will suffice.
